# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0002_auto_20170114_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesections',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagesections',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagetest2',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomePageSections',
        ),
        migrations.DeleteModel(
            name='HomePageTest2',
        ),
    ]
