# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFragments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('path', models.CharField(help_text='Relative URL', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.GenericPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='links',
            name='page',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
