# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161114_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSLinkFragments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('path', models.CharField(help_text='Relative URL', max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSLinkFragments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('path', models.CharField(help_text='Relative URL', max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='linkfragments',
            name='page',
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.DeleteModel(
            name='LinkFragments',
        ),
        migrations.AddField(
            model_name='jslinkfragments',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_links', to='home.GenericPage'),
        ),
        migrations.AddField(
            model_name='csslinkfragments',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='css_links', to='home.GenericPage'),
        ),
    ]
