# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_featuredcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcontent',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='page',
        ),
        migrations.DeleteModel(
            name='FeaturedContent',
        ),
    ]
