# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20161117_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedContentX',
            new_name='FeaturedContentSet',
        ),
    ]
