# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='font_awesome_class',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
