# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_aboutpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='icon',
            new_name='social_icon',
        ),
    ]
