# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20161209_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iconlinks',
            old_name='title',
            new_name='font_awesome_class',
        ),
        migrations.RemoveField(
            model_name='iconlinks',
            name='body',
        ),
        migrations.RemoveField(
            model_name='iconlinks',
            name='link_page',
        ),
        migrations.AddField(
            model_name='iconlinks',
            name='text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iconlinks',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
