# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20161209_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iconlinks',
            old_name='text',
            new_name='name',
        ),
    ]
