# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20161209_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.AddField(
            model_name='iconlinks',
            name='svg',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='iconlinks',
            name='font_awesome_class',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
