# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 21:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20161214_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('icon_block', wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), (b'font_awesome_class', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'svg', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock(required=False))]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock([(b'code', wagtail.wagtailcore.blocks.TextBlock(required=True)), (b'language', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'line_number', wagtail.wagtailcore.blocks.IntegerBlock(required=False))])), ('two_columns', wagtail.wagtailcore.blocks.StructBlock([(b'left_column', wagtail.wagtailcore.blocks.StreamBlock([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock([(b'code', wagtail.wagtailcore.blocks.TextBlock(required=True)), (b'language', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'line_number', wagtail.wagtailcore.blocks.IntegerBlock(required=False))]))], icon='arrow-left', label='Left column content')), (b'right_column', wagtail.wagtailcore.blocks.StreamBlock([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock([(b'code', wagtail.wagtailcore.blocks.TextBlock(required=True)), (b'language', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'line_number', wagtail.wagtailcore.blocks.IntegerBlock(required=False))]))], icon='arrow-right', label='Right column content'))]))]),
        ),
    ]
