# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20161216_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconlinks',
            name='page',
        ),
        migrations.DeleteModel(
            name='IconLinks',
        ),
    ]
