# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 13:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_indexpage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
