# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_sectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='show_siblings',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
