# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_genericpage_show_siblings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='show_siblings',
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='date',
            field=models.DateField(blank=True, verbose_name='Post date'),
        ),
    ]
