# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0036_auto_20161222_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
