# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0039_introductionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='SectionPage',
        ),
    ]
